spring.application.name=developer
Spring.datasource.url=jdbc:mysql://localhost:3306/developer_profile
Spring.datasource.username=root
Spring.datasource.Password=Nitish@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
Spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Show full Hibernate/datasource info
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.hibernate.SQL=DEBUG
jwt.secret=368fd21cddf5ca5deae72ee705f1359520a95306b78bdece04e53ded3a88bd4c71c50a4f
jwt.access-token-expiry=900000
jwt.refresh-token-expiry=604800000
frontend_url=http://localhost:5173
