spring.application.name=developer
Spring.datasource.url=${DATABASE-URL}
Spring.datasource.username=${DATABASE-USERNAME}
Spring.datasource.Password=${DATABASE-PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
Spring.jpa.properties.hibernate.dialect=${DATABASE-DIELECTRIC}
# Show full Hibernate/datasource info
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.hibernate.SQL=DEBUG
jwt.secret=${JWT-SECRET}
jwt.access-token-expiry=900000
jwt.refresh-token-expiry=604800000
frontend_url=${FRONTEND-URL}
